# Generated by Django 2.2.6 on 2019-10-04 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agricultural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cnpj', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cnpj', models.CharField(max_length=16)),
                ('nirf', models.CharField(max_length=25)),
                ('ccir', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='PartnershipFarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('agricultural', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnership_farms', to='api.Agricultural')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='api.Farm')),
                ('farmers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnership_farms', to='api.Farmer')),
            ],
        ),
        migrations.CreateModel(
            name='PartnershipAgricultural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('agricultural', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships', to='api.Farmer')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_agricultural', to='api.Farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Cadesp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nirf', models.CharField(max_length=25)),
                ('ccir', models.CharField(max_length=25)),
                ('hectar_nirf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hectar_ccir', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadesp_farm', to='api.Farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadesp_farmer', to='api.Farmer')),
            ],
        ),
    ]
